// Code generated by mockery. DO NOT EDIT.

package users

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSaveUserProcessor is an autogenerated mock type for the SaveUserProcessor type
type MockSaveUserProcessor struct {
	mock.Mock
}

// ProcessRequest provides a mock function with given fields: ctx, user
func (_m *MockSaveUserProcessor) ProcessRequest(ctx context.Context, user UserRequest) error {
	ret := _m.Called(ctx, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, UserRequest) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockSaveUserProcessor creates a new instance of MockSaveUserProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSaveUserProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSaveUserProcessor {
	mock := &MockSaveUserProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
